### ISSUE TITLE
set the width of the sidebar

### ISSUE THREAD

**Issue by kubante** [codrops/ElasticSVGElements#5]
Hi, 

I tried to tinkle with your code but do not find the setting/property that defines the width of the sidebar when opened. Could you point me in the right direction pls? 

Thanks, 

k

**Comment by AtousaDarabi** [comment]
Hi dear kubante,

please do these changes in sidebar.css file. Hope it would help you.
In .menu class change width:300px; to width:500px; and left:0; to left:-200px; .
And in .menu.menu--open class add left:0; .
These changes make your sidebar menu wider.

Atousa

**Comment by kubante** [comment]
Perfect! worked. Thank you very much Atousa!

**Comment by AtousaDarabi** [comment]
Your welcome!
